# SPDX-License-Identifier: MIT

services:
    dpdk-init:
        image: docker.io/library/oai-dpdk-init:latest
        network_mode: host
        container_name: dpdk-init
        entrypoint: "/tmp/setup_sriov.sh"
        privileged: true
        devices:
            - /dev/vfio:/dev/vfio/
        volumes:
            - ./setup_sriov_vvdn.sh:/tmp/setup_sriov.sh
            - /lib/modules:/lib/modules
            - /usr/lib/modules:/usr/lib/modules
    oai-du-high:
        image: ${REGISTRY-oaisoftwarealliance/}oai-gnb-fhi72-t2:${TAG:-develop}
        network_mode: "host"
        cap_add:
            - IPC_LOCK
            - SYS_NICE
        cap_drop:
            - ALL
        container_name: oai-du-high
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --nfapi VNF
            NFAPI_TRACE_LEVEL: info
        volumes:
            - ../../conf_files/gnb-vnf.sa.band77.273prb.fhi72.4x4-4L-vvdn.conf:/opt/oai-gnb/etc/gnb.conf
        # Please change these values based on your system
        cpuset: "24,25,26"
        healthcheck:
           test: /bin/bash -c "pgrep nr-softmodem"
           start_period: 15s
           start_interval: 500ms
           interval: 5s
           timeout: 5s
           retries: 10
    oai-du-low:
        image: ${REGISTRY-oaisoftwarealliance/}oai-gnb-fhi72-t2:${TAG:-develop}
        network_mode: "host"
        cap_add:
            - IPC_LOCK
            - SYS_NICE
        cap_drop:
            - ALL
        container_name: oai-du-low
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --nfapi PNF --thread-pool 13,14,15,16,17,18,19,20 --loader.ldpc.shlibversion _aal --log_config.global_log_options level,nocolor,utc_time
            NFAPI_TRACE_LEVEL: info
        devices:
            - /dev/vfio:/dev/vfio/
        volumes:
            - ../../conf_files/gnb-pnf.sa.band77.273prb.fhi72.4x4-4L-vvdn.conf:/opt/oai-gnb/etc/gnb.conf
            - /dev/hugepages:/dev/hugepages
        # Please change these values based on your system
        cpuset: "7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23"
        depends_on:
           dpdk-init:
             condition: service_completed_successfully
        healthcheck:
           test: /bin/bash -c "/opt/oai-gnb/bin/check-prach-io.sh"
           start_period: 15s
           start_interval: 500ms
           interval: 5s
           timeout: 5s
           retries: 10
