# SPDX-License-Identifier: LicenseRef-CSSL-1.0

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for UBI9
#
#---------------------------------------------------------------------


FROM registry.redhat.io/ubi9/ubi:latest AS ran-base
LABEL MAINTAINER OpenAirInterface <oaicicdteam@openairinterface.org>
ARG NEEDED_GIT_PROXY
ARG TARGETARCH
ENV TZ=Europe/Paris
ENV BUILD_UHD_FROM_SOURCE=True
ENV UHD_VERSION=4.8.0.0

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement

ENV SMDEV_CONTAINER_OFF=1
#install developers pkg/repo
RUN rm -f /etc/rhsm-host && \
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms && \
    dnf update -y && \
    cat /etc/os-release && \
    dnf install -y \
       #gcc needed for build_oai
       diffutils \
       file \
       psmisc \
       git \
       meson \
       wget \
       xz \
       pkg-config \
       pcre2-devel \
       m4 \
       python3-devel \
       numactl-libs \
       numactl-devel \
       #use gcc-13 to avoid problems of default gcc-11 in FlexRIC
       gcc-toolset-13-gcc \
       gcc-toolset-13-gcc-c++ \
       # python3-pip and pyyaml are used for conf template generation
       python3-pip && \
    pip3 install --ignore-installed \
       pyyaml \
       pyelftools && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Add "Tini - A tiny but valid init for containers", https://github.com/krallin/tini
# it will be copied into target containers, to print exit numbers and handle signals properly
ENV TINI_VERSION=v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${TARGETARCH} /tini
RUN chmod +x /tini

ENV YQ_VERSION=v4.2.0
RUN wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH} -O /usr/local/bin/yq &&\
    chmod +x /usr/local/bin/yq

# In some network environments, GIT proxy is required
RUN /bin/bash -c "if [[ -v NEEDED_GIT_PROXY ]]; then git config --global http.proxy $NEEDED_GIT_PROXY; fi"

# Copying only the needed files to create ran-base
WORKDIR /oai-ran/cmake_targets/tools
COPY cmake_targets/tools/build_helper \
     cmake_targets/tools/uhd-4.5plus-tdd-patch.diff \
     ./

WORKDIR /oai-ran/cmake_targets
COPY cmake_targets/build_oai .

WORKDIR /oai-ran
COPY oaienv .

#run build_oai -I to get the builder image
RUN /bin/sh oaienv && \
    cd cmake_targets && \
    mkdir -p log && \
    scl enable gcc-toolset-13 "\
    ./build_oai -I --install-optional-packages -w USRP" && \
    rm /etc/pki/entitlement/*pem
